services:
  gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./
          action: rebuild
    ports:
      - "10001:10001"
    restart: always
