services:
  node-1:
    image: hyperledger/besu:latest
    container_name: "node-1"
    volumes :
      - ./blockchain/nodes/Node-1:/usr/app/
    command: --config-file=/usr/app/config.toml
    ports:
      - "30304"
      - "8546"
    networks:
      orange_blockchain:
        ipv4_address: 172.20.0.1

  node-2:
    image: hyperledger/besu:latest
    container_name: "node-2"
    volumes:
      - ./blockchain/nodes/Node-2:/usr/app/
    command: --config-file=/usr/app/config.toml
    networks:
      orange_blockchain:
        ipv4_address: 172.20.0.2

  node-3:
    image: hyperledger/besu:latest
    container_name: "node-3"
    volumes:
      - ./blockchain/nodes/Node-3:/usr/app/
    command: --config-file=/usr/app/config.toml
    networks:
      orange_blockchain:
        ipv4_address: 172.20.0.3

  node-4:
    image: hyperledger/besu:latest
    container_name: "node-4"
    volumes:
      - ./blockchain/nodes/Node-4:/usr/app/
    command: --config-file=/usr/app/config.toml
    networks:
      orange_blockchain:
        ipv4_address: 172.20.0.4
        
  node-5:
    image: hyperledger/besu:latest
    container_name: "node-5"
    volumes:
      - ./blockchain/nodes/Node-5:/usr/app/
    command: --config-file=/usr/app/config.toml
    networks:
      orange_blockchain:
        ipv4_address: 172.20.0.5
        
  node-6:
    image: hyperledger/besu:latest
    container_name: "node-6"
    volumes:
      - ./blockchain/nodes/Node-6:/usr/app/
    command: --config-file=/usr/app/config.toml
    networks:
      orange_blockchain:
        ipv4_address: 172.20.0.6


networks:
  orange_blockchain:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/28
          gateway: 172.20.0.9