services:
  orange_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: orange.node_db
      POSTGRES_USER: orange.node_user
      POSTGRES_PASSWORD: orange.node_pass
    volumes:
      - orange_pg_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - orange_internal
    restart: always

  orange_node:
    build:
      context: ./idp_node   # path to your Spring Boot app
      dockerfile: Dockerfile  # assumes Dockerfile is in the root of spring-app
    develop:
      watch:
        - path: ./idp_node
          action: rebuild
    depends_on:
      - orange_db
    ports:
      - "8080:8080"            # change if your Spring app uses a different port
    networks:
      - orange_internal
    restart: always

  orange_idp:
    build:
      context: ./orange_idp   # path to your Spring Boot app
      dockerfile: Dockerfile  # optional if your Dockerfile is named `Dockerfile`
    ports:
      - "3000:3000"            # change port as needed
    develop:
      watch:
        - path: ./orange_idp
          action: rebuild
    restart: always


    
volumes:
  orange_pg_db:
  orange_mongo_db1:
  orange_mongo_db2:
  orange_mongo_db3:
  mongo_keyfile:
    driver: local

networks:
  orange_internal:
    driver: bridge